<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApproveDemandeDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\ApproveDemandeDto' shared autowired service.
     *
     * @return \App\DTO\ApproveDemandeDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\DTO\\ApproveDemandeDto": argument "$commentaire" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
