<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AX1pb.7.App\Controller\CategorieController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AX1pb.7.App\\Controller\\CategorieController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cat' => ['privates', '.errored..service_locator.AX1pb.7.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.AX1pb.7": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cat' => 'App\\Entity\\Categorie',
            'em' => '?',
        ]))->withContext('App\\Controller\\CategorieController::delete()', $container);
    }
}
