<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OOaON1s.App\Controller\CategorieController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OOaON1s.App\\Controller\\CategorieController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\DTO\\CreateCategorieDto', NULL, 'Cannot autowire service "App\\DTO\\CreateCategorieDto": argument "$nom" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dto' => 'App\\DTO\\CreateCategorieDto',
            'em' => '?',
        ]))->withContext('App\\Controller\\CategorieController::create()', $container);
    }
}
