<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TZEWJs5.App\Controller\DemandeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TZEWJs5.App\\Controller\\DemandeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\DemandeRepository',
        ]))->withContext('App\\Controller\\DemandeController::index()', $container);
    }
}
