<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IADUVUB.App\Entity\Demande' shared service.
     *
     * @return \App\Entity\Demande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IADUVUB": it needs an instance of "App\\Entity\\Demande" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
