<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeControllervalidateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rWh8IK2.App\Controller\DemandeController::validate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rWh8IK2.App\\Controller\\DemandeController::validate()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.rWh8IK2.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.rWh8IK2": it needs an instance of "App\\Entity\\Demande" but this type has been excluded because it\'s a Doctrine entity.'],
            'dto' => ['privates', 'App\\DTO\\ValidateDemandeDto', NULL, 'Cannot autowire service "App\\DTO\\ValidateDemandeDto": argument "$commentaire" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'dto' => 'App\\DTO\\ValidateDemandeDto',
            'em' => '?',
        ]))->withContext('App\\Controller\\DemandeController::validate()', $container);
    }
}
