<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Az7__5h.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Az7__5h.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matRepo' => ['privates', 'App\\Repository\\MaterielRepository', 'getMaterielRepositoryService', true],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'demRepo' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'matRepo' => 'App\\Repository\\MaterielRepository',
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'demRepo' => 'App\\Repository\\DemandeRepository',
            'userRepo' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
