<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XepRgD2.App\Controller\DemandeController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XepRgD2.App\\Controller\\DemandeController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\DTO\\CreateDemandeDto', NULL, 'Cannot autowire service "App\\DTO\\CreateDemandeDto": argument "$items" of method "__construct()" is type-hinted "array", you should configure its value explicitly.'],
            'matRepo' => ['privates', 'App\\Repository\\MaterielRepository', 'getMaterielRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'dto' => 'App\\DTO\\CreateDemandeDto',
            'matRepo' => 'App\\Repository\\MaterielRepository',
            'em' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\DemandeController::create()', $container);
    }
}
