<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O_jYPRu.App\Controller\MaterielController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O_jYPRu.App\\Controller\\MaterielController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'materiel' => ['privates', '.errored..service_locator.O_jYPRu.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.O_jYPRu": it needs an instance of "App\\Entity\\Materiel" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'materiel' => 'App\\Entity\\Materiel',
            'em' => '?',
        ]))->withContext('App\\Controller\\MaterielController::delete()', $container);
    }
}
