<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OvdmdOP.App\Controller\MaterielController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OvdmdOP.App\\Controller\\MaterielController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'materiel' => ['privates', '.errored..service_locator.OvdmdOP.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.OvdmdOP": it needs an instance of "App\\Entity\\Materiel" but this type has been excluded because it\'s a Doctrine entity.'],
            'dto' => ['privates', 'App\\DTO\\CreateMaterielDto', NULL, 'Cannot autowire service "App\\DTO\\CreateMaterielDto": argument "$nom" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'materiel' => 'App\\Entity\\Materiel',
            'dto' => 'App\\DTO\\CreateMaterielDto',
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'em' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\MaterielController::update()', $container);
    }
}
