<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4tCdHLd.App\Controller\MaterielController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4tCdHLd.App\\Controller\\MaterielController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\DTO\\CreateMaterielDto', NULL, 'Cannot autowire service "App\\DTO\\CreateMaterielDto": argument "$nom" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dto' => 'App\\DTO\\CreateMaterielDto',
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\MaterielController::create()', $container);
    }
}
