<?php

namespace ContainerBt6VBxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllerreadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nbJ.izH.App\Controller\NotificationController::read()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nbJ.izH.App\\Controller\\NotificationController::read()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.nbJ.izH.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.nbJ.izH": it needs an instance of "App\\Entity\\Notification" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'notification' => 'App\\Entity\\Notification',
            'em' => '?',
        ]))->withContext('App\\Controller\\NotificationController::read()', $container);
    }
}
