<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWm2h91J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWm2h91J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWm2h91J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWm2h91J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWm2h91J\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wm2h91J',
    'container.build_id' => '77452248',
    'container.build_time' => 1776609297,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWm2h91J');
