<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGQxXx7E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGQxXx7E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGQxXx7E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGQxXx7E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGQxXx7E\App_KernelDevDebugContainer([
    'container.build_hash' => 'GQxXx7E',
    'container.build_id' => '357b2847',
    'container.build_time' => 1775344138,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGQxXx7E');
