<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBt6VBxc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBt6VBxc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBt6VBxc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBt6VBxc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBt6VBxc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bt6VBxc',
    'container.build_id' => '0187adfe',
    'container.build_time' => 1772374074,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBt6VBxc');
