<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406213909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AF346686C6E55B5 ON categories (nom)');
        $this->addSql('CREATE INDEX IDX_3AF34668B03A8386 ON categories (created_by_id)');
        $this->addSql('CREATE TABLE demande_materiels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite_demandee INT NOT NULL, quantite_accordee INT DEFAULT NULL, statut VARCHAR(50) NOT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, demande_id INT NOT NULL, materiel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E93244BC80E95E18 ON demande_materiels (demande_id)');
        $this->addSql('CREATE INDEX IDX_E93244BC16880AAF ON demande_materiels (materiel_id)');
        $this->addSql('CREATE TABLE demandes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, commentaire_validation TEXT DEFAULT NULL, commentaire_approbation TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_approbation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(50) NOT NULL, utilisateur_id INT NOT NULL, comptable_matiere_id INT DEFAULT NULL, administrateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD940CBBFB88E14F ON demandes (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_BD940CBB92862200 ON demandes (comptable_matiere_id)');
        $this->addSql('CREATE INDEX IDX_BD940CBB7EE5403C ON demandes (administrateur_id)');
        $this->addSql('CREATE TABLE historiques (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_action TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, action VARCHAR(255) NOT NULL, target_entity VARCHAR(255) DEFAULT NULL, target_id INT DEFAULT NULL, details TEXT DEFAULT NULL, demande_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B25FDE8D80E95E18 ON historiques (demande_id)');
        $this->addSql('CREATE TABLE materiels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, quantite_totale INT NOT NULL, quantite_disponible INT NOT NULL, etat VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seuil_alerte INT DEFAULT 5 NOT NULL, categorie_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C1EBE69BCF5E72D ON materiels (categorie_id)');
        $this->addSql('CREATE INDEX IDX_9C1EBE69B03A8386 ON materiels (created_by_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, lu BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3FB88E14F ON notifications (utilisateur_id)');
        $this->addSql('CREATE TABLE utilisateurs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, statut VARCHAR(20) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utilisateurs (email)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668B03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_materiels ADD CONSTRAINT FK_E93244BC80E95E18 FOREIGN KEY (demande_id) REFERENCES demandes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_materiels ADD CONSTRAINT FK_E93244BC16880AAF FOREIGN KEY (materiel_id) REFERENCES materiels (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demandes ADD CONSTRAINT FK_BD940CBBFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demandes ADD CONSTRAINT FK_BD940CBB92862200 FOREIGN KEY (comptable_matiere_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demandes ADD CONSTRAINT FK_BD940CBB7EE5403C FOREIGN KEY (administrateur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historiques ADD CONSTRAINT FK_B25FDE8D80E95E18 FOREIGN KEY (demande_id) REFERENCES demandes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE materiels ADD CONSTRAINT FK_9C1EBE69BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE materiels ADD CONSTRAINT FK_9C1EBE69B03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668B03A8386');
        $this->addSql('ALTER TABLE demande_materiels DROP CONSTRAINT FK_E93244BC80E95E18');
        $this->addSql('ALTER TABLE demande_materiels DROP CONSTRAINT FK_E93244BC16880AAF');
        $this->addSql('ALTER TABLE demandes DROP CONSTRAINT FK_BD940CBBFB88E14F');
        $this->addSql('ALTER TABLE demandes DROP CONSTRAINT FK_BD940CBB92862200');
        $this->addSql('ALTER TABLE demandes DROP CONSTRAINT FK_BD940CBB7EE5403C');
        $this->addSql('ALTER TABLE historiques DROP CONSTRAINT FK_B25FDE8D80E95E18');
        $this->addSql('ALTER TABLE materiels DROP CONSTRAINT FK_9C1EBE69BCF5E72D');
        $this->addSql('ALTER TABLE materiels DROP CONSTRAINT FK_9C1EBE69B03A8386');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3FB88E14F');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE demande_materiels');
        $this->addSql('DROP TABLE demandes');
        $this->addSql('DROP TABLE historiques');
        $this->addSql('DROP TABLE materiels');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE utilisateurs');
    }
}
