<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CNaQcKIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cNaQcKI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cNaQcKI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.TTfYbRk.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.MGgJW4c.App\\Controller\\CategorieController::index()', 'getCategorieControllerindexService', true],
            'App\\Controller\\CategorieController::create' => ['privates', '.service_locator.OOaON1s.App\\Controller\\CategorieController::create()', 'getCategorieControllercreateService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.AX1pb.7.App\\Controller\\CategorieController::delete()', 'getCategorieControllerdeleteService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.Az7__5h.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DemandeController::index' => ['privates', '.service_locator.TZEWJs5.App\\Controller\\DemandeController::index()', 'getDemandeControllerindexService', true],
            'App\\Controller\\DemandeController::create' => ['privates', '.service_locator.XepRgD2.App\\Controller\\DemandeController::create()', 'getDemandeControllercreateService', true],
            'App\\Controller\\DemandeController::validate' => ['privates', '.service_locator.rWh8IK2.App\\Controller\\DemandeController::validate()', 'getDemandeControllervalidateService', true],
            'App\\Controller\\DemandeController::approve' => ['privates', '.service_locator.IADUVUB.App\\Controller\\DemandeController::approve()', 'getDemandeControllerapproveService', true],
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.fBAa6bL.App\\Controller\\MaterielController::index()', 'getMaterielControllerindexService', true],
            'App\\Controller\\MaterielController::create' => ['privates', '.service_locator.4tCdHLd.App\\Controller\\MaterielController::create()', 'getMaterielControllercreateService', true],
            'App\\Controller\\MaterielController::update' => ['privates', '.service_locator.OvdmdOP.App\\Controller\\MaterielController::update()', 'getMaterielControllerupdateService', true],
            'App\\Controller\\MaterielController::delete' => ['privates', '.service_locator.O_jYPRu.App\\Controller\\MaterielController::delete()', 'getMaterielControllerdeleteService', true],
            'App\\Controller\\NotificationController::index' => ['privates', '.service_locator.UsljUrV.App\\Controller\\NotificationController::index()', 'getNotificationControllerindexService', true],
            'App\\Controller\\NotificationController::read' => ['privates', '.service_locator.nbJ.izH.App\\Controller\\NotificationController::read()', 'getNotificationControllerreadService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.Vh5KAa7.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController::updateRole' => ['privates', '.service_locator.3uKXi_t.App\\Controller\\UtilisateurController::updateRole()', 'getUtilisateurControllerupdateRoleService', true],
            'App\\Controller\\UtilisateurController::updateStatut' => ['privates', '.service_locator.3uKXi_t.App\\Controller\\UtilisateurController::updateStatut()', 'getUtilisateurControllerupdateStatutService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.TTfYbRk.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.MGgJW4c.App\\Controller\\CategorieController::index()', 'getCategorieControllerindexService', true],
            'App\\Controller\\CategorieController:create' => ['privates', '.service_locator.OOaON1s.App\\Controller\\CategorieController::create()', 'getCategorieControllercreateService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.AX1pb.7.App\\Controller\\CategorieController::delete()', 'getCategorieControllerdeleteService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.Az7__5h.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DemandeController:index' => ['privates', '.service_locator.TZEWJs5.App\\Controller\\DemandeController::index()', 'getDemandeControllerindexService', true],
            'App\\Controller\\DemandeController:create' => ['privates', '.service_locator.XepRgD2.App\\Controller\\DemandeController::create()', 'getDemandeControllercreateService', true],
            'App\\Controller\\DemandeController:validate' => ['privates', '.service_locator.rWh8IK2.App\\Controller\\DemandeController::validate()', 'getDemandeControllervalidateService', true],
            'App\\Controller\\DemandeController:approve' => ['privates', '.service_locator.IADUVUB.App\\Controller\\DemandeController::approve()', 'getDemandeControllerapproveService', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.fBAa6bL.App\\Controller\\MaterielController::index()', 'getMaterielControllerindexService', true],
            'App\\Controller\\MaterielController:create' => ['privates', '.service_locator.4tCdHLd.App\\Controller\\MaterielController::create()', 'getMaterielControllercreateService', true],
            'App\\Controller\\MaterielController:update' => ['privates', '.service_locator.OvdmdOP.App\\Controller\\MaterielController::update()', 'getMaterielControllerupdateService', true],
            'App\\Controller\\MaterielController:delete' => ['privates', '.service_locator.O_jYPRu.App\\Controller\\MaterielController::delete()', 'getMaterielControllerdeleteService', true],
            'App\\Controller\\NotificationController:index' => ['privates', '.service_locator.UsljUrV.App\\Controller\\NotificationController::index()', 'getNotificationControllerindexService', true],
            'App\\Controller\\NotificationController:read' => ['privates', '.service_locator.nbJ.izH.App\\Controller\\NotificationController::read()', 'getNotificationControllerreadService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.Vh5KAa7.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController:updateRole' => ['privates', '.service_locator.3uKXi_t.App\\Controller\\UtilisateurController::updateRole()', 'getUtilisateurControllerupdateRoleService', true],
            'App\\Controller\\UtilisateurController:updateStatut' => ['privates', '.service_locator.3uKXi_t.App\\Controller\\UtilisateurController::updateStatut()', 'getUtilisateurControllerupdateStatutService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::create' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DemandeController::index' => '?',
            'App\\Controller\\DemandeController::create' => '?',
            'App\\Controller\\DemandeController::validate' => '?',
            'App\\Controller\\DemandeController::approve' => '?',
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::create' => '?',
            'App\\Controller\\MaterielController::update' => '?',
            'App\\Controller\\MaterielController::delete' => '?',
            'App\\Controller\\NotificationController::index' => '?',
            'App\\Controller\\NotificationController::read' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::updateRole' => '?',
            'App\\Controller\\UtilisateurController::updateStatut' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:create' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DemandeController:index' => '?',
            'App\\Controller\\DemandeController:create' => '?',
            'App\\Controller\\DemandeController:validate' => '?',
            'App\\Controller\\DemandeController:approve' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:create' => '?',
            'App\\Controller\\MaterielController:update' => '?',
            'App\\Controller\\MaterielController:delete' => '?',
            'App\\Controller\\NotificationController:index' => '?',
            'App\\Controller\\NotificationController:read' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:updateRole' => '?',
            'App\\Controller\\UtilisateurController:updateStatut' => '?',
        ]);
    }
}
