<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3uKXiTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3uKXi_t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3uKXi_t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.3uKXi_t.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.3uKXi_t": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\Utilisateur',
            'em' => '?',
        ]);
    }
}
