<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TTfYbRk.App\Controller\AuthController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TTfYbRk.App\\Controller\\AuthController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\DTO\\RegisterUserDto', NULL, 'Cannot autowire service "App\\DTO\\RegisterUserDto": argument "$nom" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'dto' => 'App\\DTO\\RegisterUserDto',
            'passwordHasher' => '?',
            'em' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\AuthController::register()', $container);
    }
}
