<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateCategorieDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\CreateCategorieDto' shared autowired service.
     *
     * @return \App\DTO\CreateCategorieDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\DTO\\CreateCategorieDto": argument "$nom" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
