<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeControllerapproveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IADUVUB.App\Controller\DemandeController::approve()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IADUVUB.App\\Controller\\DemandeController::approve()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.IADUVUB.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.IADUVUB": it needs an instance of "App\\Entity\\Demande" but this type has been excluded because it\'s a Doctrine entity.'],
            'dto' => ['privates', 'App\\DTO\\ApproveDemandeDto', NULL, 'Cannot autowire service "App\\DTO\\ApproveDemandeDto": argument "$commentaire" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'dto' => 'App\\DTO\\ApproveDemandeDto',
            'em' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\DemandeController::approve()', $container);
    }
}
