<?php

namespace ContainerJY6fJrb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fBAa6bL.App\Controller\MaterielController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fBAa6bL.App\\Controller\\MaterielController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\MaterielRepository', 'getMaterielRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\MaterielRepository',
        ]))->withContext('App\\Controller\\MaterielController::index()', $container);
    }
}
